import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GoogleAnalytics } from '@next/third-parties/google';

import './globals.css';
import { ThemeProvider } from './components/ThemeProvider';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });
const GOOGLE_ANALYTIC_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTIC_ID;

export const metadata: Metadata = {
	title: 'ApexKV',
	description: 'Generated by create next app',
	icons: '/logo.ico',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					{children}
				</ThemeProvider>
			</body>
			<GoogleAnalytics gaId={GOOGLE_ANALYTIC_ID!} />
		</html>
	);
}
